AllCops:
  Exclude:
    - db/schema.rb
    - bin/**/*
    - "spec/spec_helper.rb"
  TargetRubyVersion: 2.5.1

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"