# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>

development:
  <<: *default
  database: cms_development

test:
  <<: *default
  database: cms_test

production:
  <<: *default
  database: cms_production